development: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  encoding: unicode
  database: besthires_development

test:
  <<: *default
  database: besthires_test
  min_messages: warning

production:
  <<: *default
  database: besthires_production
